apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: ishaangulati8/basic-express:latest
          name: basic-express
