apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30